#!/usr/bin/env python
"""
Train PPO Micro-Manipulation Agent for Hybrid TAMP Pick Skill
============================================================
Trains a Stable-Baselines3 PPO policy on GraspLiftEnv to perform compliant
descent, grasp, and lift from pre-grasp hover poses generated by TaskSpaceRRT.
"""
from __future__ import annotations

import argparse
import os
import sys
import time

import torch
from stable_baselines3 import PPO
from stable_baselines3.common.callbacks import CheckpointCallback, EvalCallback
from stable_baselines3.common.monitor import Monitor

# Ensure workspace root is in sys.path
repo_root = os.path.dirname(os.path.abspath(__file__))
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)

from src.envs.grasp_lift_env import GraspLiftEnv


def parse_args():
    parser = argparse.ArgumentParser(description="Train PPO policy for robot grasp and lift")
    parser.add_argument(
        "--total-timesteps",
        type=int,
        default=25000,
        help="Total environment timesteps for PPO training (default: 25000)",
    )
    parser.add_argument(
        "--num-demos",
        type=int,
        default=100,
        help="Number of expert demonstrations for BC warm-start (default: 100, 0 to disable)",
    )
    parser.add_argument(
        "--pretrain-epochs",
        type=int,
        default=150,
        help="Number of epochs for BC pre-training (default: 150)",
    )
    parser.add_argument(
        "--save-path",
        type=str,
        default="models/ppo_hybrid_lift.zip",
        help="Path where trained model zip will be saved",
    )
    parser.add_argument(
        "--learning-rate",
        type=float,
        default=1e-4,
        help="Learning rate for Adam optimizer (default: 1e-4)",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=64,
        help="Minibatch size for PPO updates (default: 64)",
    )
    parser.add_argument(
        "--n-steps",
        type=int,
        default=1024,
        help="Number of steps to run for each environment per update (default: 1024)",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for reproducibility",
    )
    parser.add_argument(
        "--eval-freq",
        type=int,
        default=5000,
        help="Timestep frequency for policy evaluation (default: 5000)",
    )
    parser.add_argument(
        "--eval-episodes",
        type=int,
        default=10,
        help="Number of episodes per evaluation run (default: 10)",
    )
    parser.add_argument(
        "--target-name",
        type=str,
        default="yellow_cube",
        help="Specific target object name to train on (default: yellow_cube). None randomizes across all objects.",
    )
    parser.add_argument(
        "--device",
        type=str,
        default="cpu",
        help="Device to train on ('cpu' or 'cuda', default: 'cpu')",
    )
    return parser.parse_args()


def pretrain_bc(model: PPO, env: GraspLiftEnv, num_demos: int = 100, epochs: int = 150):
    """
    Collects expert demonstrations and pre-trains the PPO actor policy via supervised imitation.
    This provides a strong warm-start so PPO does not get trapped in reaching-only local minima.
    """
    import numpy as np
    print(f"\n[WARM-START] Collecting {num_demos} expert demonstrations from {env.target_name_override or 'yellow_cube'}...")
    t0 = time.time()
    obs_list, act_list = [], []

    for ep in range(num_demos):
        obs, info = env.reset()
        done = False
        step = 0
        while not done and step < env.max_steps:
            step += 1
            act = env.get_expert_action()
            obs_list.append(obs)
            act_list.append(act)
            obs, r, term, trunc, info = env.step(act)
            done = term or trunc

    print(f"[WARM-START] Collected {len(obs_list)} transitions in {time.time() - t0:.1f}s.")
    X = torch.tensor(np.array(obs_list), dtype=torch.float32)
    Y = torch.tensor(np.array(act_list), dtype=torch.float32)

    print(f"[WARM-START] Optimizing PPO policy network via supervised loss ({epochs} epochs)...")
    optimizer = torch.optim.Adam(model.policy.parameters(), lr=1e-3)
    loss_fn = torch.nn.MSELoss()

    for epoch in range(epochs):
        optimizer.zero_grad()
        dist = model.policy.get_distribution(X)
        pred = dist.mode()
        loss = loss_fn(pred, Y)
        loss.backward()
        optimizer.step()
        if (epoch + 1) % 50 == 0 or epoch == epochs - 1:
            print(f"  [BC Epoch {epoch+1:3d}/{epochs}] Policy Loss: {loss.item():.4f}")

    print("[WARM-START] Supervised pre-training complete. Commencing PPO reinforcement learning...\n")


def main():
    args = parse_args()
    print("=" * 70)
    print("PPO Hybrid Pick Training: Grasp & Lift Micro-Policy")
    print("=" * 70)
    print(f"Device:            {args.device}")
    print(f"Total Timesteps:   {args.total_timesteps}")
    print(f"Save Path:         {args.save_path}")
    print(f"Target Filter:     {args.target_name if args.target_name else 'All objects (randomized)'}")
    print(f"Demos (Warm-start):{args.num_demos}")
    print(f"Batch Size:        {args.batch_size}")
    print(f"Rollout Steps:     {args.n_steps}")
    print(f"Learning Rate:     {args.learning_rate}")
    print("=" * 70)

    # Ensure output directories exist
    save_dir = os.path.dirname(os.path.abspath(args.save_path))
    os.makedirs(save_dir, exist_ok=True)

    log_dir = os.path.join(repo_root, "logs", "ppo_training")
    os.makedirs(log_dir, exist_ok=True)

    # 1. Instantiate training environment wrapped with SB3 Monitor
    train_env = Monitor(
        GraspLiftEnv(target_name=args.target_name),
        filename=os.path.join(log_dir, "train_monitor.csv"),
    )

    # 2. Instantiate evaluation environment
    eval_env = Monitor(
        GraspLiftEnv(target_name=args.target_name),
        filename=os.path.join(log_dir, "eval_monitor.csv"),
    )

    # 3. Setup evaluation callback
    best_model_dir = os.path.join(save_dir, "best_model")
    os.makedirs(best_model_dir, exist_ok=True)

    eval_callback = EvalCallback(
        eval_env,
        best_model_save_path=best_model_dir,
        log_path=log_dir,
        eval_freq=args.eval_freq,
        n_eval_episodes=args.eval_episodes,
        deterministic=True,
        render=False,
    )

    # 4. Policy architecture
    policy_kwargs = dict(
        net_arch=dict(pi=[128, 128], vf=[128, 128]),
        activation_fn=torch.nn.ReLU,
    )

    # 5. Initialize PPO agent
    model = PPO(
        policy="MlpPolicy",
        env=train_env,
        learning_rate=args.learning_rate,
        n_steps=args.n_steps,
        batch_size=args.batch_size,
        n_epochs=10,
        gamma=0.99,
        gae_lambda=0.95,
        clip_range=0.2,
        ent_coef=0.005,
        vf_coef=0.5,
        max_grad_norm=0.5,
        policy_kwargs=policy_kwargs,
        verbose=1,
        seed=args.seed,
        device=args.device,
        tensorboard_log=log_dir,
    )

    # 6. Optional BC Warm-Start Pretraining
    if args.num_demos > 0:
        raw_train_env = train_env.env if hasattr(train_env, "env") else train_env
        pretrain_bc(model, raw_train_env, num_demos=args.num_demos, epochs=args.pretrain_epochs)

    start_time = time.time()
    print(f"\nStarting PPO training for {args.total_timesteps} steps...")

    try:
        model.learn(
            total_timesteps=args.total_timesteps,
            callback=eval_callback,
            progress_bar=False,
        )
    except KeyboardInterrupt:
        print("\n[WARNING] Training interrupted by user. Saving current checkpoint...")

    elapsed = time.time() - start_time
    print(f"\nTraining completed in {elapsed:.1f}s.")

    # Save final model
    model.save(args.save_path)
    print(f"[SUCCESS] Model successfully saved to {args.save_path}")

    train_env.close()
    eval_env.close()


if __name__ == "__main__":
    main()
